name: Build and Push docker image

on:
  push:
    branches:    
      - deploy

jobs:
  BuildAndPush:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CODEDEPLOY_LAMBDA1: lok-dev-ngs-deploy-after-allow-test-traffic
      CODEDEPLOY_LAMBDA2: lok-dev-ngs-deploy-after-allow-traffic

    steps:
      - uses: actions/checkout@v1

      # Set AWS cli credentials to be used with following steps
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Login to ECR
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1

      # Build and push docker image
      - name: Build, tag, and push image to Amazon ECR
        env:
          ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          ECR_REPOSITORY: lok-dev-ngs
          IMAGE_TAG: ${{ github.sha }}
        run: |
          docker build -t $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG -t $ECR_REGISTRY/$ECR_REPOSITORY:latest .
          docker images
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG
          docker push $ECR_REGISTRY/$ECR_REPOSITORY:latest  
      
      - name: Build and push CodeDeploy lambdas
        run: |
          cd .github/workflows/codedeploy/lambda/AfterAllowTestTraffic
          python -m pip install -r requirements.txt -t .
          zip -rq ./lambda.zip ./
          aws lambda update-function-code --function-name $CODEDEPLOY_LAMBDA1 --zip-file fileb://lambda.zip

          cd $GITHUB_WORKSPACE && cd .github/workflows/codedeploy/lambda/AfterAllowTraffic
          python -m pip install -r requirements.txt -t .
          zip -rq ./lambda.zip ./
          aws lambda update-function-code --function-name $CODEDEPLOY_LAMBDA2 --zip-file fileb://lambda.zip


  Deploy:
    needs: [ BuildAndPush ]
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      CODEDEPLOY_APPSPEC_S3_URI: s3://lok-dev-appspec/ngs/appspec.yaml

    steps:
      - uses: actions/checkout@v1

      # Set AWS cli credentials to be used with following steps
      - name: Set AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      # Initiate deployment in CodeDeploy
      - name: Deploy
        run: |
          cd .github/workflows/codedeploy
          aws s3 cp appspec.yaml $CODEDEPLOY_APPSPEC_S3_URI
          aws deploy create-deployment --cli-input-json file://create-deployment.json
      
      - name: Deployment status URL
        run: |
          echo "Please visit CodeDeploy console for the deployment status:"
          echo "https://console.aws.amazon.com/codesuite/codedeploy/deployments?region=$AWS_REGION" 